// fonte = https://pokemondb.net/sprites
const pokemonList = [
  {
    Id: 1,
    Name: "Bulbasaur",
    Type: 'Grass',
    Total: 318,
    HP: 45,
    Attack: 49,
    Defense: 49,
    SpAtk: 65,
    SpDef: 65,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/bulbasaur",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/bulbasaur.gif"
  },
  {
    Id: 2,
    Name: "Ivysaur",
    Type: 'Grass',
    Total: 405,
    HP: 60,
    Attack: 62,
    Defense: 63,
    SpAtk: 80,
    SpDef: 80,
    Speed: 60,
    MoreInfo: "http://pokemondb.net/pokedex/ivysaur",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/ivysaur.gif"
  },
  {
    Id: 3,
    Name: "Venusaur",
    Type: 'Grass',
    Total: 525,
    HP: 80,
    Attack: 82,
    Defense: 83,
    SpAtk: 100,
    SpDef: 100,
    Speed: 80,
    MoreInfo: "http://pokemondb.net/pokedex/venusaur",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif"
  },
  {
    Id: 4,
    Name: "Charmander",
    Type: 'Fire',
    Total: 309,
    HP: 39,
    Attack: 52,
    Defense: 43,
    SpAtk: 60,
    SpDef: 50,
    Speed: 65,
    MoreInfo: "http://pokemondb.net/pokedex/charmander",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/charmander.gif"
  },
  {
    Id: 5,
    Name: "Charmeleon",
    Type: 'Fire',
    Total: 405,
    HP: 58,
    Attack: 64,
    Defense: 58,
    SpAtk: 80,
    SpDef: 65,
    Speed: 80,
    MoreInfo: "http://pokemondb.net/pokedex/charmeleon",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/charmeleon.gif"
  },
  {
    Id: 6,
    Name: "Charizard",
    Type: 'Fire',
    Total: 534,
    HP: 78,
    Attack: 84,
    Defense: 78,
    SpAtk: 109,
    SpDef: 85,
    Speed: 100,
    MoreInfo: "http://pokemondb.net/pokedex/charizard",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif"
  },
  {
    Id: 7,
    Name: "Squirtle",
    Type: 'Water',
    Total: 314,
    HP: 44,
    Attack: 48,
    Defense: 65,
    SpAtk: 50,
    SpDef: 64,
    Speed: 43,
    MoreInfo: "http://pokemondb.net/pokedex/squirtle",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/squirtle.gif"
  },
  {
    Id: 8,
    Name: "Wartortle",
    Type: 'Water',
    Total: 405,
    HP: 59,
    Attack: 63,
    Defense: 80,
    SpAtk: 65,
    SpDef: 80,
    Speed: 58,
    MoreInfo: "http://pokemondb.net/pokedex/wartortle",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/wartortle.gif"
  },
  {
    Id: 9,
    Name: "Blastoise",
    Type: 'Water',
    Total: 530,
    HP: 79,
    Attack: 83,
    Defense: 100,
    SpAtk: 85,
    SpDef: 105,
    Speed: 78,
    MoreInfo: "http://pokemondb.net/pokedex/blastoise",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif"
  },
  {
    Id: 10,
    Name: "Caterpie",
    Type: 'Bug',
    Total: 195,
    HP: 45,
    Attack: 30,
    Defense: 35,
    SpAtk: 20,
    SpDef: 20,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/caterpie",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/caterpie.gif"
  },
  {
    Id: 11,
    Name: "Metapod",
    Type: 'Bug',
    Total: 205,
    HP: 50,
    Attack: 20,
    Defense: 55,
    SpAtk: 25,
    SpDef: 25,
    Speed: 30,
    MoreInfo: "http://pokemondb.net/pokedex/metapod",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/metapod.gif"
  },
  {
    Id: 12,
    Name: "Butterfree",
    Type: 'Bug',
    Total: 395,
    HP: 60,
    Attack: 45,
    Defense: 50,
    SpAtk: 90,
    SpDef: 80,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/butterfree",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/butterfree.gif"
  },
  {
    Id: 13,
    Name: "Weedle",
    Type: 'Bug',
    Total: 195,
    HP: 40,
    Attack: 35,
    Defense: 30,
    SpAtk: 20,
    SpDef: 20,
    Speed: 50,
    MoreInfo: "http://pokemondb.net/pokedex/weedle",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/weedle.gif"
  },
  {
    Id: 14,
    Name: "Kakuna",
    Type: 'Bug',
    Total: 205,
    HP: 45,
    Attack: 25,
    Defense: 50,
    SpAtk: 25,
    SpDef: 25,
    Speed: 35,
    MoreInfo: "http://pokemondb.net/pokedex/kakuna",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/kakuna.gif"
  },
  {
    Id: 15,
    Name: "Beedrill",
    Type: 'Bug',
    Total: 395,
    HP: 65,
    Attack: 90,
    Defense: 40,
    SpAtk: 45,
    SpDef: 80,
    Speed: 75,
    MoreInfo: "http://pokemondb.net/pokedex/beedrill",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/beedrill.gif"
  },
  {
    Id: 16,
    Name: "Pidgey",
    Type: 'Normal',
    Total: 251,
    HP: 40,
    Attack: 45,
    Defense: 40,
    SpAtk: 35,
    SpDef: 35,
    Speed: 56,
    MoreInfo: "http://pokemondb.net/pokedex/pidgey",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgey.gif"
  },
  {
    Id: 17,
    Name: "Pidgeotto",
    Type: 'Normal',
    Total: 349,
    HP: 63,
    Attack: 60,
    Defense: 55,
    SpAtk: 50,
    SpDef: 50,
    Speed: 71,
    MoreInfo: "http://pokemondb.net/pokedex/pidgeotto",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeotto.gif"
  },
  {
    Id: 18,
    Name: "Pidgeot",
    Type: 'Normal',
    Total: 479,
    HP: 83,
    Attack: 80,
    Defense: 75,
    SpAtk: 70,
    SpDef: 70,
    Speed: 101,
    MoreInfo: "http://pokemondb.net/pokedex/pidgeot",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif"
  },
  {
    Id: 19,
    Name: "Rattata",
    Type: 'Normal',
    Total: 253,
    HP: 30,
    Attack: 56,
    Defense: 35,
    SpAtk: 25,
    SpDef: 35,
    Speed: 72,
    MoreInfo: "http://pokemondb.net/pokedex/rattata",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/rattata.gif"
  },
  {
    Id: 20,
    Name: "Raticate",
    Type: 'Normal',
    Total: 413,
    HP: 55,
    Attack: 81,
    Defense: 60,
    SpAtk: 50,
    SpDef: 70,
    Speed: 97,
    MoreInfo: "http://pokemondb.net/pokedex/raticate",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/raticate.gif"
  },
  {
    Id: 21,
    Name: "Spearow",
    Type: 'Normal',
    Total: 262,
    HP: 40,
    Attack: 60,
    Defense: 30,
    SpAtk: 31,
    SpDef: 31,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/spearow",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/spearow.gif"
  },
  {
    Id: 22,
    Name: "Fearow",
    Type: 'Normal',
    Total: 442,
    HP: 65,
    Attack: 90,
    Defense: 65,
    SpAtk: 61,
    SpDef: 61,
    Speed: 100,
    MoreInfo: "http://pokemondb.net/pokedex/fearow",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/fearow.gif"
  },
  {
    Id: 23,
    Name: "Ekans",
    Type: 'Poison',
    Total: 288,
    HP: 35,
    Attack: 60,
    Defense: 44,
    SpAtk: 40,
    SpDef: 54,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/ekans",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/ekans.gif"
  },
  {
    Id: 24,
    Name: "Arbok",
    Type: 'Poison',
    Total: 448,
    HP: 60,
    Attack: 95,
    Defense: 69,
    SpAtk: 65,
    SpDef: 79,
    Speed: 80,
    MoreInfo: "http://pokemondb.net/pokedex/arbok",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif"
  },
  {
    Id: 25,
    Name: "Pikachu",
    Type: 'Electric',
    Total: 320,
    HP: 35,
    Attack: 55,
    Defense: 40,
    SpAtk: 50,
    SpDef: 50,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/pikachu",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/pikachu.gif"
  },
  {
    Id: 26,
    Name: "Raichu",
    Type: 'Electric',
    Total: 485,
    HP: 60,
    Attack: 90,
    Defense: 55,
    SpAtk: 90,
    SpDef: 80,
    Speed: 110,
    MoreInfo: "http://pokemondb.net/pokedex/raichu",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif"
  },
  {
    Id: 27,
    Name: "Sandshrew",
    Type: 'Ground',
    Total: 300,
    HP: 50,
    Attack: 75,
    Defense: 85,
    SpAtk: 20,
    SpDef: 30,
    Speed: 40,
    MoreInfo: "http://pokemondb.net/pokedex/sandshrew",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/sandshrew.gif"
  },
  {
    Id: 28,
    Name: "Sandslash",
    Type: 'Ground',
    Total: 450,
    HP: 75,
    Attack: 100,
    Defense: 110,
    SpAtk: 45,
    SpDef: 55,
    Speed: 65,
    MoreInfo: "http://pokemondb.net/pokedex/sandslash",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/sandslash.gif"
  },
  {
    Id: 29,
    Name: "Nidoran♀",
    Type: 'Poison',
    Total: 275,
    HP: 55,
    Attack: 47,
    Defense: 52,
    SpAtk: 40,
    SpDef: 40,
    Speed: 41,
    MoreInfo: "http://pokemondb.net/pokedex/nidoran-f",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-f.gif"
  },
  {
    Id: 30,
    Name: "Nidorina",
    Type: 'Poison',
    Total: 365,
    HP: 70,
    Attack: 62,
    Defense: 67,
    SpAtk: 55,
    SpDef: 55,
    Speed: 56,
    MoreInfo: "http://pokemondb.net/pokedex/nidorina",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidorina.gif"
  },
  {
    Id: 31,
    Name: "Nidoqueen",
    Type: 'Poison',
    Total: 505,
    HP: 90,
    Attack: 92,
    Defense: 87,
    SpAtk: 75,
    SpDef: 85,
    Speed: 76,
    MoreInfo: "http://pokemondb.net/pokedex/nidoqueen",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif"
  },
  {
    Id: 32,
    Name: "Nidoran♂",
    Type: 'Poison',
    Total: 273,
    HP: 46,
    Attack: 57,
    Defense: 40,
    SpAtk: 40,
    SpDef: 40,
    Speed: 50,
    MoreInfo: "http://pokemondb.net/pokedex/nidoran-m",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-m.gif"
  },
  {
    Id: 33,
    Name: "Nidorino",
    Type: 'Poison',
    Total: 365,
    HP: 61,
    Attack: 72,
    Defense: 57,
    SpAtk: 55,
    SpDef: 55,
    Speed: 65,
    MoreInfo: "http://pokemondb.net/pokedex/nidorino",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidorino.gif"
  },
  {
    Id: 34,
    Name: "Nidoking",
    Type: 'Poison',
    Total: 505,
    HP: 81,
    Attack: 102,
    Defense: 77,
    SpAtk: 85,
    SpDef: 75,
    Speed: 85,
    MoreInfo: "http://pokemondb.net/pokedex/nidoking",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif"
  },
  {
    Id: 35,
    Name: "Clefairy",
    Type: 'Fairy',
    Total: 323,
    HP: 70,
    Attack: 45,
    Defense: 48,
    SpAtk: 60,
    SpDef: 65,
    Speed: 35,
    MoreInfo: "http://pokemondb.net/pokedex/clefairy",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/clefairy.gif"
  },
  {
    Id: 36,
    Name: "Clefable",
    Type: 'Fairy',
    Total: 483,
    HP: 95,
    Attack: 70,
    Defense: 73,
    SpAtk: 95,
    SpDef: 90,
    Speed: 60,
    MoreInfo: "http://pokemondb.net/pokedex/clefable",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif"
  },
  {
    Id: 37,
    Name: "Vulpix",
    Type: 'Fire',
    Total: 299,
    HP: 38,
    Attack: 41,
    Defense: 40,
    SpAtk: 50,
    SpDef: 65,
    Speed: 65,
    MoreInfo: "http://pokemondb.net/pokedex/vulpix",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/vulpix.gif"
  },
  {
    Id: 38,
    Name: "Ninetales",
    Type: 'Fire',
    Total: 505,
    HP: 73,
    Attack: 76,
    Defense: 75,
    SpAtk: 81,
    SpDef: 100,
    Speed: 100,
    MoreInfo: "http://pokemondb.net/pokedex/ninetales",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif"
  },
  {
    Id: 39,
    Name: "Jigglypuff",
    Type: 'Fairy',
    Total: 270,
    HP: 115,
    Attack: 45,
    Defense: 20,
    SpAtk: 45,
    SpDef: 25,
    Speed: 20,
    MoreInfo: "http://pokemondb.net/pokedex/jigglypuff",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/jigglypuff.gif"
  },
  {
    Id: 40,
    Name: "Wigglytuff",
    Type: 'Fairy',
    Total: 435,
    HP: 140,
    Attack: 70,
    Defense: 45,
    SpAtk: 85,
    SpDef: 50,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/wigglytuff",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/wigglytuff.gif"
  },
  {
    Id: 41,
    Name: "Zubat",
    Type: 'Poison',
    Total: 245,
    HP: 40,
    Attack: 45,
    Defense: 35,
    SpAtk: 30,
    SpDef: 40,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/zubat",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/zubat.gif"
  },
  {
    Id: 42,
    Name: "Golbat",
    Type: 'Poison',
    Total: 455,
    HP: 75,
    Attack: 80,
    Defense: 70,
    SpAtk: 65,
    SpDef: 75,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/golbat",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/golbat.gif"
  },
  {
    Id: 43,
    Name: "Oddish",
    Type: 'Grass',
    Total: 320,
    HP: 45,
    Attack: 50,
    Defense: 55,
    SpAtk: 75,
    SpDef: 65,
    Speed: 30,
    MoreInfo: "http://pokemondb.net/pokedex/oddish",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/oddish.gif"
  },
  {
    Id: 44,
    Name: "Gloom",
    Type: 'Grass',
    Total: 395,
    HP: 60,
    Attack: 65,
    Defense: 70,
    SpAtk: 85,
    SpDef: 75,
    Speed: 40,
    MoreInfo: "http://pokemondb.net/pokedex/gloom",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/gloom.gif"
  },
  {
    Id: 45,
    Name: "Vileplume",
    Type: 'Grass',
    Total: 490,
    HP: 75,
    Attack: 80,
    Defense: 85,
    SpAtk: 110,
    SpDef: 90,
    Speed: 50,
    MoreInfo: "http://pokemondb.net/pokedex/vileplume",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif"
  },
  {
    Id: 46,
    Name: "Paras",
    Type: 'Bug',
    Total: 285,
    HP: 35,
    Attack: 70,
    Defense: 55,
    SpAtk: 45,
    SpDef: 55,
    Speed: 25,
    MoreInfo: "http://pokemondb.net/pokedex/paras",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/paras.gif"
  },
  {
    Id: 47,
    Name: "Parasect",
    Type: 'Bug',
    Total: 405,
    HP: 60,
    Attack: 95,
    Defense: 80,
    SpAtk: 60,
    SpDef: 80,
    Speed: 30,
    MoreInfo: "http://pokemondb.net/pokedex/parasect",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/parasect.gif"
  },
  {
    Id: 48,
    Name: "Venonat",
    Type: 'Bug',
    Total: 305,
    HP: 60,
    Attack: 55,
    Defense: 50,
    SpAtk: 40,
    SpDef: 55,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/venonat",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/venonat.gif"
  },
  {
    Id: 49,
    Name: "Venomoth",
    Type: 'Bug',
    Total: 450,
    HP: 70,
    Attack: 65,
    Defense: 60,
    SpAtk: 90,
    SpDef: 75,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/venomoth",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/venomoth.gif"
  },
  {
    Id: 50,
    Name: "Diglett",
    Type: 'Ground',
    Total: 265,
    HP: 10,
    Attack: 55,
    Defense: 25,
    SpAtk: 35,
    SpDef: 45,
    Speed: 95,
    MoreInfo: "http://pokemondb.net/pokedex/diglett",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/diglett.gif"
  },
  {
    Id: 51,
    Name: "Dugtrio",
    Type: 'Ground',
    Total: 425,
    HP: 35,
    Attack: 100,
    Defense: 50,
    SpAtk: 50,
    SpDef: 70,
    Speed: 120,
    MoreInfo: "http://pokemondb.net/pokedex/dugtrio",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/dugtrio.gif"
  },
  {
    Id: 52,
    Name: "Meowth",
    Type: 'Normal',
    Total: 290,
    HP: 40,
    Attack: 45,
    Defense: 35,
    SpAtk: 40,
    SpDef: 40,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/meowth",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/meowth.gif"
  },
  {
    Id: 53,
    Name: "Persian",
    Type: 'Normal',
    Total: 440,
    HP: 65,
    Attack: 70,
    Defense: 60,
    SpAtk: 65,
    SpDef: 65,
    Speed: 115,
    MoreInfo: "http://pokemondb.net/pokedex/persian",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif"
  },
  {
    Id: 54,
    Name: "Psyduck",
    Type: 'Water',
    Total: 320,
    HP: 50,
    Attack: 52,
    Defense: 48,
    SpAtk: 65,
    SpDef: 50,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/psyduck",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/psyduck.gif"
  },
  {
    Id: 55,
    Name: "Golduck",
    Type: 'Water',
    Total: 500,
    HP: 80,
    Attack: 82,
    Defense: 78,
    SpAtk: 95,
    SpDef: 80,
    Speed: 85,
    MoreInfo: "http://pokemondb.net/pokedex/golduck",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif"
  },
  {
    Id: 56,
    Name: "Mankey",
    Type: 'Fighting',
    Total: 305,
    HP: 40,
    Attack: 80,
    Defense: 35,
    SpAtk: 35,
    SpDef: 45,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/mankey",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/mankey.gif"
  },
  {
    Id: 57,
    Name: "Primeape",
    Type: 'Fighting',
    Total: 455,
    HP: 65,
    Attack: 105,
    Defense: 60,
    SpAtk: 60,
    SpDef: 70,
    Speed: 95,
    MoreInfo: "http://pokemondb.net/pokedex/primeape",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif"
  },
  {
    Id: 58,
    Name: "Growlithe",
    Type: 'Fire',
    Total: 350,
    HP: 55,
    Attack: 70,
    Defense: 45,
    SpAtk: 70,
    SpDef: 50,
    Speed: 60,
    MoreInfo: "http://pokemondb.net/pokedex/growlithe",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/growlithe.gif"
  },
  {
    Id: 59,
    Name: "Arcanine",
    Type: 'Fire',
    Total: 555,
    HP: 90,
    Attack: 110,
    Defense: 80,
    SpAtk: 100,
    SpDef: 80,
    Speed: 95,
    MoreInfo: "http://pokemondb.net/pokedex/arcanine",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif"
  },
  {
    Id: 60,
    Name: "Poliwag",
    Type: 'Water',
    Total: 300,
    HP: 40,
    Attack: 50,
    Defense: 40,
    SpAtk: 40,
    SpDef: 40,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/poliwag",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwag.gif"
  },
  {
    Id: 61,
    Name: "Poliwhirl",
    Type: 'Water',
    Total: 385,
    HP: 65,
    Attack: 65,
    Defense: 65,
    SpAtk: 50,
    SpDef: 50,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/poliwhirl",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwhirl.gif"
  },
  {
    Id: 62,
    Name: "Poliwrath",
    Type: 'Water',
    Total: 510,
    HP: 90,
    Attack: 95,
    Defense: 95,
    SpAtk: 70,
    SpDef: 90,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/poliwrath",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif"
  },
  {
    Id: 63,
    Name: "Abra",
    Type: 'Psychic',
    Total: 310,
    HP: 25,
    Attack: 20,
    Defense: 15,
    SpAtk: 105,
    SpDef: 55,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/abra",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/abra.gif"
  },
  {
    Id: 64,
    Name: "Kadabra",
    Type: 'Psychic',
    Total: 400,
    HP: 40,
    Attack: 35,
    Defense: 30,
    SpAtk: 120,
    SpDef: 70,
    Speed: 105,
    MoreInfo: "http://pokemondb.net/pokedex/kadabra",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/kadabra.gif"
  },
  {
    Id: 65,
    Name: "Alakazam",
    Type: 'Psychic',
    Total: 500,
    HP: 55,
    Attack: 50,
    Defense: 45,
    SpAtk: 135,
    SpDef: 95,
    Speed: 120,
    MoreInfo: "http://pokemondb.net/pokedex/alakazam",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif"
  },
  {
    Id: 66,
    Name: "Machop",
    Type: 'Fighting',
    Total: 305,
    HP: 70,
    Attack: 80,
    Defense: 50,
    SpAtk: 35,
    SpDef: 35,
    Speed: 35,
    MoreInfo: "http://pokemondb.net/pokedex/machop",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/machop.gif"
  },
  {
    Id: 67,
    Name: "Machoke",
    Type: 'Fighting',
    Total: 405,
    HP: 80,
    Attack: 100,
    Defense: 70,
    SpAtk: 50,
    SpDef: 60,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/machoke",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/machoke.gif"
  },
  {
    Id: 68,
    Name: "Machamp",
    Type: 'Fighting',
    Total: 505,
    HP: 90,
    Attack: 130,
    Defense: 80,
    SpAtk: 65,
    SpDef: 85,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/machamp",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif"
  },
  {
    Id: 69,
    Name: "Bellsprout",
    Type: 'Grass',
    Total: 300,
    HP: 50,
    Attack: 75,
    Defense: 35,
    SpAtk: 70,
    SpDef: 30,
    Speed: 40,
    MoreInfo: "http://pokemondb.net/pokedex/bellsprout",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/bellsprout.gif"
  },
  {
    Id: 70,
    Name: "Weepinbell",
    Type: 'Grass',
    Total: 390,
    HP: 65,
    Attack: 90,
    Defense: 50,
    SpAtk: 85,
    SpDef: 45,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/weepinbell",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/weepinbell.gif"
  },
  {
    Id: 71,
    Name: "Victreebel",
    Type: 'Grass',
    Total: 490,
    HP: 80,
    Attack: 105,
    Defense: 65,
    SpAtk: 100,
    SpDef: 70,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/victreebel",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif"
  },
  {
    Id: 72,
    Name: "Tentacool",
    Type: 'Water',
    Total: 335,
    HP: 40,
    Attack: 40,
    Defense: 35,
    SpAtk: 50,
    SpDef: 100,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/tentacool",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/tentacool.gif"
  },
  {
    Id: 73,
    Name: "Tentacruel",
    Type: 'Water',
    Total: 515,
    HP: 80,
    Attack: 70,
    Defense: 65,
    SpAtk: 80,
    SpDef: 120,
    Speed: 100,
    MoreInfo: "http://pokemondb.net/pokedex/tentacruel",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/tentacruel.gif"
  },
  {
    Id: 74,
    Name: "Geodude",
    Type: 'Rock',
    Total: 300,
    HP: 40,
    Attack: 80,
    Defense: 100,
    SpAtk: 30,
    SpDef: 30,
    Speed: 20,
    MoreInfo: "http://pokemondb.net/pokedex/geodude",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/geodude.gif"
  },
  {
    Id: 75,
    Name: "Graveler",
    Type: 'Rock',
    Total: 390,
    HP: 55,
    Attack: 95,
    Defense: 115,
    SpAtk: 45,
    SpDef: 45,
    Speed: 35,
    MoreInfo: "http://pokemondb.net/pokedex/graveler",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/graveler.gif"
  },
  {
    Id: 76,
    Name: "Golem",
    Type: 'Rock',
    Total: 495,
    HP: 80,
    Attack: 120,
    Defense: 130,
    SpAtk: 55,
    SpDef: 65,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/golem",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif"
  },
  {
    Id: 77,
    Name: "Ponyta",
    Type: 'Fire',
    Total: 410,
    HP: 50,
    Attack: 85,
    Defense: 55,
    SpAtk: 65,
    SpDef: 65,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/ponyta",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/ponyta.gif"
  },
  {
    Id: 78,
    Name: "Rapidash",
    Type: 'Fire',
    Total: 500,
    HP: 65,
    Attack: 100,
    Defense: 70,
    SpAtk: 80,
    SpDef: 80,
    Speed: 105,
    MoreInfo: "http://pokemondb.net/pokedex/rapidash",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif"
  },
  {
    Id: 79,
    Name: "Slowpoke",
    Type: 'Water',
    Total: 315,
    HP: 90,
    Attack: 65,
    Defense: 65,
    SpAtk: 40,
    SpDef: 40,
    Speed: 15,
    MoreInfo: "http://pokemondb.net/pokedex/slowpoke",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/slowpoke.gif"
  },
  {
    Id: 80,
    Name: "Slowbro",
    Type: 'Water',
    Total: 490,
    HP: 95,
    Attack: 75,
    Defense: 110,
    SpAtk: 100,
    SpDef: 80,
    Speed: 30,
    MoreInfo: "http://pokemondb.net/pokedex/slowbro",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif"
  },
  {
    Id: 81,
    Name: "Magnemite",
    Type: 'Steel',
    Total: 325,
    HP: 25,
    Attack: 35,
    Defense: 70,
    SpAtk: 95,
    SpDef: 55,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/magnemite",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/magnemite.gif"
  },
  {
    Id: 82,
    Name: "Magneton",
    Type: 'Steel',
    Total: 465,
    HP: 50,
    Attack: 60,
    Defense: 95,
    SpAtk: 120,
    SpDef: 70,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/magneton",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif"
  },
  {
    Id: 83,
    Name: "Farfetch'd",
    Type: 'Normal',
    Total: 377,
    HP: 52,
    Attack: 90,
    Defense: 55,
    SpAtk: 58,
    SpDef: 62,
    Speed: 60,
    MoreInfo: "http://pokemondb.net/pokedex/farfetchd",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/farfetchd.gif"
  },
  {
    Id: 84,
    Name: "Doduo",
    Type: 'Normal',
    Total: 310,
    HP: 35,
    Attack: 85,
    Defense: 45,
    SpAtk: 35,
    SpDef: 35,
    Speed: 75,
    MoreInfo: "http://pokemondb.net/pokedex/doduo",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/doduo.gif"
  },
  {
    Id: 85,
    Name: "Dodrio",
    Type: 'Normal',
    Total: 470,
    HP: 60,
    Attack: 110,
    Defense: 70,
    SpAtk: 60,
    SpDef: 60,
    Speed: 110,
    MoreInfo: "http://pokemondb.net/pokedex/dodrio",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif"
  },
  {
    Id: 86,
    Name: "Seel",
    Type: 'Water',
    Total: 325,
    HP: 65,
    Attack: 45,
    Defense: 55,
    SpAtk: 45,
    SpDef: 70,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/seel",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/seel.gif"
  },
  {
    Id: 87,
    Name: "Dewgong",
    Type: 'Ice',
    Total: 475,
    HP: 90,
    Attack: 70,
    Defense: 80,
    SpAtk: 70,
    SpDef: 95,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/dewgong",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif"
  },
  {
    Id: 88,
    Name: "Grimer",
    Type: 'Poison',
    Total: 325,
    HP: 80,
    Attack: 80,
    Defense: 50,
    SpAtk: 40,
    SpDef: 50,
    Speed: 25,
    MoreInfo: "http://pokemondb.net/pokedex/grimer",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/grimer.gif"
  },
  {
    Id: 89,
    Name: "Muk",
    Type: 'Poison',
    Total: 500,
    HP: 105,
    Attack: 105,
    Defense: 75,
    SpAtk: 65,
    SpDef: 100,
    Speed: 50,
    MoreInfo: "http://pokemondb.net/pokedex/muk",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif"
  },
  {
    Id: 90,
    Name: "Shellder",
    Type: 'Water',
    Total: 305,
    HP: 30,
    Attack: 65,
    Defense: 100,
    SpAtk: 45,
    SpDef: 25,
    Speed: 40,
    MoreInfo: "http://pokemondb.net/pokedex/shellder",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/shellder.gif"
  },
  {
    Id: 91,
    Name: "Cloyster",
    Type: 'Ice',
    Total: 525,
    HP: 50,
    Attack: 95,
    Defense: 180,
    SpAtk: 85,
    SpDef: 45,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/cloyster",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif"
  },
  {
    Id: 92,
    Name: "Gastly",
    Type: 'Ghost',
    Total: 310,
    HP: 30,
    Attack: 35,
    Defense: 30,
    SpAtk: 100,
    SpDef: 35,
    Speed: 80,
    MoreInfo: "http://pokemondb.net/pokedex/gastly",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/gastly.gif"
  },
  {
    Id: 93,
    Name: "Haunter",
    Type: 'Ghost',
    Total: 405,
    HP: 45,
    Attack: 50,
    Defense: 45,
    SpAtk: 115,
    SpDef: 55,
    Speed: 95,
    MoreInfo: "http://pokemondb.net/pokedex/haunter",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/haunter.gif"
  },
  {
    Id: 94,
    Name: "Gengar",
    Type: 'Ghost',
    Total: 500,
    HP: 60,
    Attack: 65,
    Defense: 60,
    SpAtk: 130,
    SpDef: 75,
    Speed: 110,
    MoreInfo: "http://pokemondb.net/pokedex/gengar",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif"
  },
  {
    Id: 95,
    Name: "Onix",
    Type: 'Rock',
    Total: 385,
    HP: 35,
    Attack: 45,
    Defense: 160,
    SpAtk: 30,
    SpDef: 45,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/onix",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif"
  },
  {
    Id: 96,
    Name: "Drowzee",
    Type: 'Psychic',
    Total: 328,
    HP: 60,
    Attack: 48,
    Defense: 45,
    SpAtk: 43,
    SpDef: 90,
    Speed: 42,
    MoreInfo: "http://pokemondb.net/pokedex/drowzee",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/drowzee.gif"
  },
  {
    Id: 97,
    Name: "Hypno",
    Type: 'Psychic',
    Total: 483,
    HP: 85,
    Attack: 73,
    Defense: 70,
    SpAtk: 73,
    SpDef: 115,
    Speed: 67,
    MoreInfo: "http://pokemondb.net/pokedex/hypno",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif"
  },
  {
    Id: 98,
    Name: "Krabby",
    Type: 'Water',
    Total: 325,
    HP: 30,
    Attack: 105,
    Defense: 90,
    SpAtk: 25,
    SpDef: 25,
    Speed: 50,
    MoreInfo: "http://pokemondb.net/pokedex/krabby",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/krabby.gif"
  },
  {
    Id: 99,
    Name: "Kingler",
    Type: 'Water',
    Total: 475,
    HP: 55,
    Attack: 130,
    Defense: 115,
    SpAtk: 50,
    SpDef: 50,
    Speed: 75,
    MoreInfo: "http://pokemondb.net/pokedex/kingler",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/kingler.gif"
  },
  {
    Id: 100,
    Name: "Voltorb",
    Type: 'Electric',
    Total: 330,
    HP: 40,
    Attack: 30,
    Defense: 50,
    SpAtk: 55,
    SpDef: 55,
    Speed: 100,
    MoreInfo: "http://pokemondb.net/pokedex/voltorb",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/voltorb.gif"
  },
  {
    Id: 101,
    Name: "Electrode",
    Type: 'Electric',
    Total: 490,
    HP: 60,
    Attack: 50,
    Defense: 70,
    SpAtk: 80,
    SpDef: 80,
    Speed: 150,
    MoreInfo: "http://pokemondb.net/pokedex/electrode",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif"
  },
  {
    Id: 102,
    Name: "Exeggcute",
    Type: 'Grass',
    Total: 325,
    HP: 60,
    Attack: 40,
    Defense: 80,
    SpAtk: 60,
    SpDef: 45,
    Speed: 40,
    MoreInfo: "http://pokemondb.net/pokedex/exeggcute",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/exeggcute.gif"
  },
  {
    Id: 103,
    Name: "Exeggutor",
    Type: 'Grass',
    Total: 530,
    HP: 95,
    Attack: 95,
    Defense: 85,
    SpAtk: 125,
    SpDef: 75,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/exeggutor",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif"
  },
  {
    Id: 104,
    Name: "Cubone",
    Type: 'Ground',
    Total: 320,
    HP: 50,
    Attack: 50,
    Defense: 95,
    SpAtk: 40,
    SpDef: 50,
    Speed: 35,
    MoreInfo: "http://pokemondb.net/pokedex/cubone",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/cubone.gif"
  },
  {
    Id: 105,
    Name: "Marowak",
    Type: 'Ground',
    Total: 425,
    HP: 60,
    Attack: 80,
    Defense: 110,
    SpAtk: 50,
    SpDef: 80,
    Speed: 45,
    MoreInfo: "http://pokemondb.net/pokedex/marowak",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/marowak.gif"
  },
  {
    Id: 106,
    Name: "Hitmonlee",
    Type: 'Fighting',
    Total: 455,
    HP: 50,
    Attack: 120,
    Defense: 53,
    SpAtk: 35,
    SpDef: 110,
    Speed: 87,
    MoreInfo: "http://pokemondb.net/pokedex/hitmonlee",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif"
  },
  {
    Id: 107,
    Name: "Hitmonchan",
    Type: 'Fighting',
    Total: 455,
    HP: 50,
    Attack: 105,
    Defense: 79,
    SpAtk: 35,
    SpDef: 110,
    Speed: 76,
    MoreInfo: "http://pokemondb.net/pokedex/hitmonchan",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif"
  },
  {
    Id: 108,
    Name: "Lickitung",
    Type: 'Normal',
    Total: 385,
    HP: 90,
    Attack: 55,
    Defense: 75,
    SpAtk: 60,
    SpDef: 75,
    Speed: 30,
    MoreInfo: "http://pokemondb.net/pokedex/lickitung",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/lickitung.gif"
  },
  {
    Id: 109,
    Name: "Koffing",
    Type: 'Poison',
    Total: 340,
    HP: 40,
    Attack: 65,
    Defense: 95,
    SpAtk: 60,
    SpDef: 45,
    Speed: 35,
    MoreInfo: "http://pokemondb.net/pokedex/koffing",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/koffing.gif"
  },
  {
    Id: 110,
    Name: "Weezing",
    Type: 'Poison',
    Total: 490,
    HP: 65,
    Attack: 90,
    Defense: 120,
    SpAtk: 85,
    SpDef: 70,
    Speed: 60,
    MoreInfo: "http://pokemondb.net/pokedex/weezing",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/weezing.gif"
  },
  {
    Id: 111,
    Name: "Rhyhorn",
    Type: 'Ground',
    Total: 345,
    HP: 80,
    Attack: 85,
    Defense: 95,
    SpAtk: 30,
    SpDef: 30,
    Speed: 25,
    MoreInfo: "http://pokemondb.net/pokedex/rhyhorn",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/rhyhorn.gif"
  },
  {
    Id: 112,
    Name: "Rhydon",
    Type: 'Ground',
    Total: 485,
    HP: 105,
    Attack: 130,
    Defense: 120,
    SpAtk: 45,
    SpDef: 45,
    Speed: 40,
    MoreInfo: "http://pokemondb.net/pokedex/rhydon",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon.gif"
  },
  {
    Id: 113,
    Name: "Chansey",
    Type: 'Normal',
    Total: 450,
    HP: 250,
    Attack: 5,
    Defense: 5,
    SpAtk: 35,
    SpDef: 105,
    Speed: 50,
    MoreInfo: "http://pokemondb.net/pokedex/chansey",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/chansey.gif"
  },
  {
    Id: 114,
    Name: "Tangela",
    Type: 'Grass',
    Total: 435,
    HP: 65,
    Attack: 55,
    Defense: 115,
    SpAtk: 100,
    SpDef: 40,
    Speed: 60,
    MoreInfo: "http://pokemondb.net/pokedex/tangela",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/tangela.gif"
  },
  {
    Id: 115,
    Name: "Kangaskhan",
    Type: 'Normal',
    Total: 490,
    HP: 105,
    Attack: 95,
    Defense: 80,
    SpAtk: 40,
    SpDef: 80,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/kangaskhan",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/kangaskhan.gif"
  },
  {
    Id: 116,
    Name: "Horsea",
    Type: 'Water',
    Total: 295,
    HP: 30,
    Attack: 40,
    Defense: 70,
    SpAtk: 70,
    SpDef: 25,
    Speed: 60,
    MoreInfo: "http://pokemondb.net/pokedex/horsea",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/horsea.gif"
  },
  {
    Id: 117,
    Name: "Seadra",
    Type: 'Water',
    Total: 440,
    HP: 55,
    Attack: 65,
    Defense: 95,
    SpAtk: 95,
    SpDef: 45,
    Speed: 85,
    MoreInfo: "http://pokemondb.net/pokedex/seadra",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/seadra.gif"
  },
  {
    Id: 118,
    Name: "Goldeen",
    Type: 'Water',
    Total: 320,
    HP: 45,
    Attack: 67,
    Defense: 60,
    SpAtk: 35,
    SpDef: 50,
    Speed: 63,
    MoreInfo: "http://pokemondb.net/pokedex/goldeen",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/goldeen.gif"
  },
  {
    Id: 119,
    Name: "Seaking",
    Type: 'Water',
    Total: 450,
    HP: 80,
    Attack: 92,
    Defense: 65,
    SpAtk: 65,
    SpDef: 80,
    Speed: 68,
    MoreInfo: "http://pokemondb.net/pokedex/seaking",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/seaking.gif"
  },
  {
    Id: 120,
    Name: "Staryu",
    Type: 'Water',
    Total: 340,
    HP: 30,
    Attack: 45,
    Defense: 55,
    SpAtk: 70,
    SpDef: 55,
    Speed: 85,
    MoreInfo: "http://pokemondb.net/pokedex/staryu",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/staryu.gif"
  },
  {
    Id: 121,
    Name: "Starmie",
    Type: 'Water',
    Total: 520,
    HP: 60,
    Attack: 75,
    Defense: 85,
    SpAtk: 100,
    SpDef: 85,
    Speed: 115,
    MoreInfo: "http://pokemondb.net/pokedex/starmie",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/starmie.gif"
  },
  {
    Id: 122,
    Name: "Mr. Mime",
    Type: 'Psychic',
    Total: 460,
    HP: 40,
    Attack: 45,
    Defense: 65,
    SpAtk: 100,
    SpDef: 120,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/mr-mime",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/mr-mime.gif"
  },
  {
    Id: 123,
    Name: "Scyther",
    Type: 'Bug',
    Total: 500,
    HP: 70,
    Attack: 110,
    Defense: 80,
    SpAtk: 55,
    SpDef: 80,
    Speed: 105,
    MoreInfo: "http://pokemondb.net/pokedex/scyther",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/scyther.gif"
  },
  {
    Id: 124,
    Name: "Jynx",
    Type: 'Psychic',
    Total: 455,
    HP: 65,
    Attack: 50,
    Defense: 35,
    SpAtk: 115,
    SpDef: 95,
    Speed: 95,
    MoreInfo: "http://pokemondb.net/pokedex/jynx",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/jynx.gif"
  },
  {
    Id: 125,
    Name: "Electabuzz",
    Type: 'Electric',
    Total: 490,
    HP: 65,
    Attack: 83,
    Defense: 57,
    SpAtk: 95,
    SpDef: 85,
    Speed: 105,
    MoreInfo: "http://pokemondb.net/pokedex/electabuzz",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/electabuzz.gif"
  },
  {
    Id: 126,
    Name: "Magmar",
    Type: 'Fire',
    Total: 495,
    HP: 65,
    Attack: 95,
    Defense: 57,
    SpAtk: 100,
    SpDef: 85,
    Speed: 93,
    MoreInfo: "http://pokemondb.net/pokedex/magmar",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/magmar.gif"
  },
  {
    Id: 127,
    Name: "Pinsir",
    Type: 'Bug',
    Total: 500,
    HP: 65,
    Attack: 125,
    Defense: 100,
    SpAtk: 55,
    SpDef: 70,
    Speed: 85,
    MoreInfo: "http://pokemondb.net/pokedex/pinsir",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/pinsir.gif"
  },
  {
    Id: 128,
    Name: "Tauros",
    Type: 'Normal',
    Total: 490,
    HP: 75,
    Attack: 100,
    Defense: 95,
    SpAtk: 40,
    SpDef: 70,
    Speed: 110,
    MoreInfo: "http://pokemondb.net/pokedex/tauros",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/tauros.gif"
  },
  {
    Id: 129,
    Name: "Magikarp",
    Type: 'Water',
    Total: 200,
    HP: 20,
    Attack: 10,
    Defense: 55,
    SpAtk: 15,
    SpDef: 20,
    Speed: 80,
    MoreInfo: "http://pokemondb.net/pokedex/magikarp",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/magikarp.gif"
  },
  {
    Id: 130,
    Name: "Gyarados",
    Type: 'Water',
    Total: 540,
    HP: 95,
    Attack: 125,
    Defense: 79,
    SpAtk: 60,
    SpDef: 100,
    Speed: 81,
    MoreInfo: "http://pokemondb.net/pokedex/gyarados",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif"
  },
  {
    Id: 131,
    Name: "Lapras",
    Type: 'Ice',
    Total: 535,
    HP: 130,
    Attack: 85,
    Defense: 80,
    SpAtk: 85,
    SpDef: 95,
    Speed: 60,
    MoreInfo: "http://pokemondb.net/pokedex/lapras",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/lapras.gif"
  },
  {
    Id: 132,
    Name: "Ditto",
    Type: 'Normal',
    Total: 288,
    HP: 48,
    Attack: 48,
    Defense: 48,
    SpAtk: 48,
    SpDef: 48,
    Speed: 48,
    MoreInfo: "http://pokemondb.net/pokedex/ditto",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/ditto.gif"
  },
  {
    Id: 133,
    Name: "Eevee",
    Type: 'Normal',
    Total: 325,
    HP: 55,
    Attack: 55,
    Defense: 50,
    SpAtk: 45,
    SpDef: 65,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/eevee",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/eevee.gif"
  },
  {
    Id: 134,
    Name: "Vaporeon",
    Type: 'Water',
    Total: 525,
    HP: 130,
    Attack: 65,
    Defense: 60,
    SpAtk: 110,
    SpDef: 95,
    Speed: 65,
    MoreInfo: "http://pokemondb.net/pokedex/vaporeon",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/vaporeon.gif"
  },
  {
    Id: 135,
    Name: "Jolteon",
    Type: 'Electric',
    Total: 525,
    HP: 65,
    Attack: 65,
    Defense: 60,
    SpAtk: 110,
    SpDef: 95,
    Speed: 130,
    MoreInfo: "http://pokemondb.net/pokedex/jolteon",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/jolteon.gif"
  },
  {
    Id: 136,
    Name: "Flareon",
    Type: 'Fire',
    Total: 525,
    HP: 65,
    Attack: 130,
    Defense: 60,
    SpAtk: 95,
    SpDef: 110,
    Speed: 65,
    MoreInfo: "http://pokemondb.net/pokedex/flareon",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/flareon.gif"
  },
  {
    Id: 137,
    Name: "Porygon",
    Type: 'Normal',
    Total: 395,
    HP: 65,
    Attack: 60,
    Defense: 70,
    SpAtk: 85,
    SpDef: 75,
    Speed: 40,
    MoreInfo: "http://pokemondb.net/pokedex/porygon",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/porygon.gif"
  },
  {
    Id: 138,
    Name: "Omanyte",
    Type: 'Rock',
    Total: 355,
    HP: 35,
    Attack: 40,
    Defense: 100,
    SpAtk: 90,
    SpDef: 55,
    Speed: 35,
    MoreInfo: "http://pokemondb.net/pokedex/omanyte",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/omanyte.gif"
  },
  {
    Id: 139,
    Name: "Omastar",
    Type: 'Rock',
    Total: 495,
    HP: 70,
    Attack: 60,
    Defense: 125,
    SpAtk: 115,
    SpDef: 70,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/omastar",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/omastar.gif"
  },
  {
    Id: 140,
    Name: "Kabuto",
    Type: 'Rock',
    Total: 355,
    HP: 30,
    Attack: 80,
    Defense: 90,
    SpAtk: 55,
    SpDef: 45,
    Speed: 55,
    MoreInfo: "http://pokemondb.net/pokedex/kabuto",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/kabuto.gif"
  },
  {
    Id: 141,
    Name: "Kabutops",
    Type: 'Rock',
    Total: 495,
    HP: 60,
    Attack: 115,
    Defense: 105,
    SpAtk: 65,
    SpDef: 70,
    Speed: 80,
    MoreInfo: "http://pokemondb.net/pokedex/kabutops",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/kabutops.gif"
  },
  {
    Id: 142,
    Name: "Aerodactyl",
    Type: 'Rock',
    Total: 515,
    HP: 80,
    Attack: 105,
    Defense: 65,
    SpAtk: 60,
    SpDef: 75,
    Speed: 130,
    MoreInfo: "http://pokemondb.net/pokedex/aerodactyl",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif"
  },
  {
    Id: 143,
    Name: "Snorlax",
    Type: 'Normal',
    Total: 540,
    HP: 160,
    Attack: 110,
    Defense: 65,
    SpAtk: 65,
    SpDef: 110,
    Speed: 30,
    MoreInfo: "http://pokemondb.net/pokedex/snorlax",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif"
  },
  {
    Id: 144,
    Name: "Articuno",
    Type: 'Ice',
    Total: 580,
    HP: 90,
    Attack: 85,
    Defense: 100,
    SpAtk: 95,
    SpDef: 125,
    Speed: 85,
    MoreInfo: "http://pokemondb.net/pokedex/articuno",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/articuno.gif"
  },
  {
    Id: 145,
    Name: "Zapdos",
    Type: 'Electric',
    Total: 580,
    HP: 90,
    Attack: 90,
    Defense: 85,
    SpAtk: 125,
    SpDef: 90,
    Speed: 100,
    MoreInfo: "http://pokemondb.net/pokedex/zapdos",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/zapdos.gif"
  },
  {
    Id: 146,
    Name: "Moltres",
    Type: 'Fire',
    Total: 580,
    HP: 90,
    Attack: 100,
    Defense: 90,
    SpAtk: 125,
    SpDef: 85,
    Speed: 90,
    MoreInfo: "http://pokemondb.net/pokedex/moltres",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/moltres.gif"
  },
  {
    Id: 147,
    Name: "Dratini",
    Type: 'Dragon',
    Total: 300,
    HP: 41,
    Attack: 64,
    Defense: 45,
    SpAtk: 50,
    SpDef: 50,
    Speed: 50,
    MoreInfo: "http://pokemondb.net/pokedex/dratini",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/dratini.gif"
  },
  {
    Id: 148,
    Name: "Dragonair",
    Type: 'Dragon',
    Total: 420,
    HP: 61,
    Attack: 84,
    Defense: 65,
    SpAtk: 70,
    SpDef: 70,
    Speed: 70,
    MoreInfo: "http://pokemondb.net/pokedex/dragonair",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/dragonair.gif"
  },
  {
    Id: 149,
    Name: "Dragonite",
    Type: 'Dragon',
    Total: 600,
    HP: 91,
    Attack: 134,
    Defense: 95,
    SpAtk: 100,
    SpDef: 100,
    Speed: 80,
    MoreInfo: "http://pokemondb.net/pokedex/dragonite",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif"
  },
  {
    Id: 150,
    Name: "Mewtwo",
    Type: 'Psychic',
    Total: 680,
    HP: 106,
    Attack: 110,
    Defense: 90,
    SpAtk: 154,
    SpDef: 90,
    Speed: 130,
    MoreInfo: "http://pokemondb.net/pokedex/mewtwo",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif"
  },
  {
    Id: 151,
    Name: "Mew",
    Type: 'Psychic',
    Total: 600,
    HP: 100,
    Attack: 100,
    Defense: 100,
    SpAtk: 100,
    SpDef: 100,
    Speed: 100,
    MoreInfo: "http://pokemondb.net/pokedex/mew",
    Image: "https://img.pokemondb.net/sprites/black-white/anim/normal/mew.gif"
  }
];

export default pokemonList;